using backendData.Models;
using System.Collections.Generic;
using System.Linq;

namespace backendData
{
    public static class backendDbSeedData
    {
        public static void EnsureSeedData(this backendDbContext db)
        {
            EnsureCountriesSeedData(db);
            EnsureUsersSeedData(db);
        }

        private static void EnsureCountriesSeedData(backendDbContext db)
        {
            if (!db.Countries.Any())
            {
                var countries = new List<Country>
                {
                    new Country { Iso2Code = "AF", Iso3Code = "AFG", Name = "Afghanistan", Continent = "AS" },
                    new Country { Iso2Code = "AX", Iso3Code = "ALA", Name = "Aland Islands", Continent = "EU" },
                    new Country { Iso2Code = "AL", Iso3Code = "ALB", Name = "Albania", Continent = "EU" },
                    new Country { Iso2Code = "DZ", Iso3Code = "DZA", Name = "Algeria", Continent = "AF" },
                    new Country { Iso2Code = "AS", Iso3Code = "ASM", Name = "American Samoa", Continent = "OC" },
                    new Country { Iso2Code = "AD", Iso3Code = "AND", Name = "Andorra", Continent = "EU" },
                    new Country { Iso2Code = "AO", Iso3Code = "AGO", Name = "Angola", Continent = "AF" },
                    new Country { Iso2Code = "AI", Iso3Code = "AIA", Name = "Anguilla", Continent = "NA" },
                    new Country { Iso2Code = "AQ", Iso3Code = "ATA", Name = "Antarctica", Continent = "AN" },
                    new Country { Iso2Code = "AG", Iso3Code = "ATG", Name = "Antigua and Barbuda", Continent = "NA" },
                    new Country { Iso2Code = "AR", Iso3Code = "ARG", Name = "Argentina", Continent = "SA" },
                    new Country { Iso2Code = "AM", Iso3Code = "ARM", Name = "Armenia", Continent = "AS" },
                    new Country { Iso2Code = "AW", Iso3Code = "ABW", Name = "Aruba", Continent = "NA" },
                    new Country { Iso2Code = "AU", Iso3Code = "AUS", Name = "Australia", Continent = "OC" },
                    new Country { Iso2Code = "AT", Iso3Code = "AUT", Name = "Austria", Continent = "EU" },
                    new Country { Iso2Code = "AZ", Iso3Code = "AZE", Name = "Azerbaijan", Continent = "AS" },
                    new Country { Iso2Code = "BS", Iso3Code = "BHS", Name = "Bahamas", Continent = "NA" },
                    new Country { Iso2Code = "BH", Iso3Code = "BHR", Name = "Bahrain", Continent = "AS" },
                    new Country { Iso2Code = "BD", Iso3Code = "BGD", Name = "Bangladesh", Continent = "AS" },
                    new Country { Iso2Code = "BB", Iso3Code = "BRB", Name = "Barbados", Continent = "NA" },
                    new Country { Iso2Code = "BY", Iso3Code = "BLR", Name = "Belarus", Continent = "EU" },
                    new Country { Iso2Code = "BE", Iso3Code = "BEL", Name = "Belgium", Continent = "EU" },
                    new Country { Iso2Code = "BZ", Iso3Code = "BLZ", Name = "Belize", Continent = "NA" },
                    new Country { Iso2Code = "BJ", Iso3Code = "BEN", Name = "Benin", Continent = "AF" },
                    new Country { Iso2Code = "BM", Iso3Code = "BMU", Name = "Bermuda", Continent = "NA" },
                    new Country { Iso2Code = "BT", Iso3Code = "BTN", Name = "Bhutan", Continent = "AS" },
                    new Country { Iso2Code = "BO", Iso3Code = "BOL", Name = "Bolivia", Continent = "SA" },
                    new Country { Iso2Code = "BQ", Iso3Code = "BES", Name = "Bonaire, Sint Eustatius and Saba", Continent = "NA" },
                    new Country { Iso2Code = "BA", Iso3Code = "BIH", Name = "Bosnia and Herzegovina", Continent = "EU" },
                    new Country { Iso2Code = "BW", Iso3Code = "BWA", Name = "Botswana", Continent = "AF" },
                    new Country { Iso2Code = "BV", Iso3Code = "BVT", Name = "Bouvet Island", Continent = "AN" },
                    new Country { Iso2Code = "BR", Iso3Code = "BRA", Name = "Brazil", Continent = "SA" },
                    new Country { Iso2Code = "VG", Iso3Code = "VGB", Name = "British Virgin Islands", Continent = "NA" },
                    new Country { Iso2Code = "IO", Iso3Code = "IOT", Name = "British Indian Ocean Territory", Continent = "AS" },
                    new Country { Iso2Code = "BN", Iso3Code = "BRN", Name = "Brunei Darussalam", Continent = "AS" },
                    new Country { Iso2Code = "BG", Iso3Code = "BGR", Name = "Bulgaria", Continent = "EU" },
                    new Country { Iso2Code = "BF", Iso3Code = "BFA", Name = "Burkina Faso", Continent = "AF" },
                    new Country { Iso2Code = "BI", Iso3Code = "BDI", Name = "Burundi", Continent = "AF" },
                    new Country { Iso2Code = "KH", Iso3Code = "KHM", Name = "Cambodia", Continent = "AS" },
                    new Country { Iso2Code = "CM", Iso3Code = "CMR", Name = "Cameroon", Continent = "AF" },
                    new Country { Iso2Code = "CA", Iso3Code = "CAN", Name = "Canada", Continent = "NA" },
                    new Country { Iso2Code = "CV", Iso3Code = "CPV", Name = "Cape Verde", Continent = "AF" },
                    new Country { Iso2Code = "KY", Iso3Code = "CYM", Name = "Cayman Islands", Continent = "NA" },
                    new Country { Iso2Code = "CF", Iso3Code = "CAF", Name = "Central African Republic", Continent = "AF" },
                    new Country { Iso2Code = "TD", Iso3Code = "TCD", Name = "Chad", Continent = "AF" },
                    new Country { Iso2Code = "CL", Iso3Code = "CHL", Name = "Chile", Continent = "SA" },
                    new Country { Iso2Code = "CN", Iso3Code = "CHN", Name = "China", Continent = "AS" },
                    new Country { Iso2Code = "HK", Iso3Code = "HKG", Name = "Hong Kong, Special Administrative Region of China", Continent = "AS" },
                    new Country { Iso2Code = "MO", Iso3Code = "MAC", Name = "Macao, Special Administrative Region of China", Continent = "AS" },
                    new Country { Iso2Code = "CX", Iso3Code = "CXR", Name = "Christmas Island", Continent = "AS" },
                    new Country { Iso2Code = "CC", Iso3Code = "CCK", Name = "Cocos (Keeling) Islands", Continent = "AS" },
                    new Country { Iso2Code = "CO", Iso3Code = "COL", Name = "Colombia", Continent = "SA" },
                    new Country { Iso2Code = "KM", Iso3Code = "COM", Name = "Comoros", Continent = "AF" },
                    new Country { Iso2Code = "CG", Iso3Code = "COG", Name = "Congo (Brazzaville)", Continent = "AF" },
                    new Country { Iso2Code = "CD", Iso3Code = "COD", Name = "Congo, Democratic Republic of the", Continent = "AF" },
                    new Country { Iso2Code = "CK", Iso3Code = "COK", Name = "Cook Islands", Continent = "OC" },
                    new Country { Iso2Code = "CR", Iso3Code = "CRI", Name = "Costa Rica", Continent = "NA" },
                    new Country { Iso2Code = "CI", Iso3Code = "CIV", Name = "Côte d'Ivoire", Continent = "AF" },
                    new Country { Iso2Code = "HR", Iso3Code = "HRV", Name = "Croatia", Continent = "EU" },
                    new Country { Iso2Code = "CU", Iso3Code = "CUB", Name = "Cuba", Continent = "NA" },
                    new Country { Iso2Code = "CW", Iso3Code = "CUW", Name = "Curaçao", Continent = "NA" },
                    new Country { Iso2Code = "CY", Iso3Code = "CYP", Name = "Cyprus", Continent = "EU" },
                    new Country { Iso2Code = "CZ", Iso3Code = "CZE", Name = "Czech Republic", Continent = "EU" },
                    new Country { Iso2Code = "DK", Iso3Code = "DNK", Name = "Denmark", Continent = "EU" },
                    new Country { Iso2Code = "DJ", Iso3Code = "DJI", Name = "Djibouti", Continent = "AF" },
                    new Country { Iso2Code = "DM", Iso3Code = "DMA", Name = "Dominica", Continent = "NA" },
                    new Country { Iso2Code = "DO", Iso3Code = "DOM", Name = "Dominican Republic", Continent = "NA" },
                    new Country { Iso2Code = "EC", Iso3Code = "ECU", Name = "Ecuador", Continent = "SA" },
                    new Country { Iso2Code = "EG", Iso3Code = "EGY", Name = "Egypt", Continent = "AF" },
                    new Country { Iso2Code = "SV", Iso3Code = "SLV", Name = "El Salvador", Continent = "NA" },
                    new Country { Iso2Code = "GQ", Iso3Code = "GNQ", Name = "Equatorial Guinea", Continent = "AF" },
                    new Country { Iso2Code = "ER", Iso3Code = "ERI", Name = "Eritrea", Continent = "AF" },
                    new Country { Iso2Code = "EE", Iso3Code = "EST", Name = "Estonia", Continent = "EU" },
                    new Country { Iso2Code = "ET", Iso3Code = "ETH", Name = "Ethiopia", Continent = "AF" },
                    new Country { Iso2Code = "FK", Iso3Code = "FLK", Name = "Falkland Islands (Malvinas)", Continent = "SA" },
                    new Country { Iso2Code = "FO", Iso3Code = "FRO", Name = "Faroe Islands", Continent = "EU" },
                    new Country { Iso2Code = "FJ", Iso3Code = "FJI", Name = "Fiji", Continent = "OC" },
                    new Country { Iso2Code = "FI", Iso3Code = "FIN", Name = "Finland", Continent = "EU" },
                    new Country { Iso2Code = "FR", Iso3Code = "FRA", Name = "France", Continent = "EU" },
                    new Country { Iso2Code = "GF", Iso3Code = "GUF", Name = "French Guiana", Continent = "SA" },
                    new Country { Iso2Code = "PF", Iso3Code = "PYF", Name = "French Polynesia", Continent = "OC" },
                    new Country { Iso2Code = "TF", Iso3Code = "ATF", Name = "French Southern Territories", Continent = "AN" },
                    new Country { Iso2Code = "GA", Iso3Code = "GAB", Name = "Gabon", Continent = "AF" },
                    new Country { Iso2Code = "GM", Iso3Code = "GMB", Name = "Gambia", Continent = "AF" },
                    new Country { Iso2Code = "GE", Iso3Code = "GEO", Name = "Georgia", Continent = "AS" },
                    new Country { Iso2Code = "DE", Iso3Code = "DEU", Name = "Germany", Continent = "EU" },
                    new Country { Iso2Code = "GH", Iso3Code = "GHA", Name = "Ghana", Continent = "AF" },
                    new Country { Iso2Code = "GI", Iso3Code = "GIB", Name = "Gibraltar", Continent = "EU" },
                    new Country { Iso2Code = "GR", Iso3Code = "GRC", Name = "Greece", Continent = "EU" },
                    new Country { Iso2Code = "GL", Iso3Code = "GRL", Name = "Greenland", Continent = "NA" },
                    new Country { Iso2Code = "GD", Iso3Code = "GRD", Name = "Grenada", Continent = "NA" },
                    new Country { Iso2Code = "GP", Iso3Code = "GLP", Name = "Guadeloupe", Continent = "NA" },
                    new Country { Iso2Code = "GU", Iso3Code = "GUM", Name = "Guam", Continent = "OC" },
                    new Country { Iso2Code = "GT", Iso3Code = "GTM", Name = "Guatemala", Continent = "NA" },
                    new Country { Iso2Code = "GG", Iso3Code = "GGY", Name = "Guernsey", Continent = "EU" },
                    new Country { Iso2Code = "GN", Iso3Code = "GIN", Name = "Guinea", Continent = "AF" },
                    new Country { Iso2Code = "GW", Iso3Code = "GNB", Name = "Guinea-Bissau", Continent = "AF" },
                    new Country { Iso2Code = "GY", Iso3Code = "GUY", Name = "Guyana", Continent = "SA" },
                    new Country { Iso2Code = "HT", Iso3Code = "HTI", Name = "Haiti", Continent = "NA" },
                    new Country { Iso2Code = "HM", Iso3Code = "HMD", Name = "Heard Island and Mcdonald Islands", Continent = "AN" },
                    new Country { Iso2Code = "VA", Iso3Code = "VAT", Name = "Holy See (Vatican City State)", Continent = "EU" },
                    new Country { Iso2Code = "HN", Iso3Code = "HND", Name = "Honduras", Continent = "NA" },
                    new Country { Iso2Code = "HU", Iso3Code = "HUN", Name = "Hungary", Continent = "EU" },
                    new Country { Iso2Code = "IS", Iso3Code = "ISL", Name = "Iceland", Continent = "EU" },
                    new Country { Iso2Code = "IN", Iso3Code = "IND", Name = "India", Continent = "AS" },
                    new Country { Iso2Code = "ID", Iso3Code = "IDN", Name = "Indonesia", Continent = "AS" },
                    new Country { Iso2Code = "IR", Iso3Code = "IRN", Name = "Iran, Islamic Republic of", Continent = "AS" },
                    new Country { Iso2Code = "IQ", Iso3Code = "IRQ", Name = "Iraq", Continent = "AS" },
                    new Country { Iso2Code = "IE", Iso3Code = "IRL", Name = "Ireland", Continent = "EU" },
                    new Country { Iso2Code = "IM", Iso3Code = "IMN", Name = "Isle of Man", Continent = "EU" },
                    new Country { Iso2Code = "IL", Iso3Code = "ISR", Name = "Israel", Continent = "AS" },
                    new Country { Iso2Code = "IT", Iso3Code = "ITA", Name = "Italy", Continent = "EU" },
                    new Country { Iso2Code = "JM", Iso3Code = "JAM", Name = "Jamaica", Continent = "NA" },
                    new Country { Iso2Code = "JP", Iso3Code = "JPN", Name = "Japan", Continent = "AS" },
                    new Country { Iso2Code = "JE", Iso3Code = "JEY", Name = "Jersey", Continent = "EU" },
                    new Country { Iso2Code = "JO", Iso3Code = "JOR", Name = "Jordan", Continent = "AS" },
                    new Country { Iso2Code = "KZ", Iso3Code = "KAZ", Name = "Kazakhstan", Continent = "AS" },
                    new Country { Iso2Code = "KE", Iso3Code = "KEN", Name = "Kenya", Continent = "AF" },
                    new Country { Iso2Code = "KI", Iso3Code = "KIR", Name = "Kiribati", Continent = "OC" },
                    new Country { Iso2Code = "KP", Iso3Code = "PRK", Name = "Korea, Democratic People's Republic of", Continent = "AS" },
                    new Country { Iso2Code = "KR", Iso3Code = "KOR", Name = "Korea, Republic of", Continent = "AS" },
                    new Country { Iso2Code = "KW", Iso3Code = "KWT", Name = "Kuwait", Continent = "AS" },
                    new Country { Iso2Code = "KG", Iso3Code = "KGZ", Name = "Kyrgyzstan", Continent = "AS" },
                    new Country { Iso2Code = "LA", Iso3Code = "LAO", Name = "Lao PDR", Continent = "AS" },
                    new Country { Iso2Code = "LV", Iso3Code = "LVA", Name = "Latvia", Continent = "EU" },
                    new Country { Iso2Code = "LB", Iso3Code = "LBN", Name = "Lebanon", Continent = "AS" },
                    new Country { Iso2Code = "LS", Iso3Code = "LSO", Name = "Lesotho", Continent = "AF" },
                    new Country { Iso2Code = "LR", Iso3Code = "LBR", Name = "Liberia", Continent = "AF" },
                    new Country { Iso2Code = "LY", Iso3Code = "LBY", Name = "Libya", Continent = "AF" },
                    new Country { Iso2Code = "LI", Iso3Code = "LIE", Name = "Liechtenstein", Continent = "EU" },
                    new Country { Iso2Code = "LT", Iso3Code = "LTU", Name = "Lithuania", Continent = "EU" },
                    new Country { Iso2Code = "LU", Iso3Code = "LUX", Name = "Luxembourg", Continent = "EU" },
                    new Country { Iso2Code = "MK", Iso3Code = "MKD", Name = "Macedonia, Republic of", Continent = "EU" },
                    new Country { Iso2Code = "MG", Iso3Code = "MDG", Name = "Madagascar", Continent = "AF" },
                    new Country { Iso2Code = "MW", Iso3Code = "MWI", Name = "Malawi", Continent = "AF" },
                    new Country { Iso2Code = "MY", Iso3Code = "MYS", Name = "Malaysia", Continent = "AS" },
                    new Country { Iso2Code = "MV", Iso3Code = "MDV", Name = "Maldives", Continent = "AS" },
                    new Country { Iso2Code = "ML", Iso3Code = "MLI", Name = "Mali", Continent = "AF" },
                    new Country { Iso2Code = "MT", Iso3Code = "MLT", Name = "Malta", Continent = "EU" },
                    new Country { Iso2Code = "MH", Iso3Code = "MHL", Name = "Marshall Islands", Continent = "OC" },
                    new Country { Iso2Code = "MQ", Iso3Code = "MTQ", Name = "Martinique", Continent = "NA" },
                    new Country { Iso2Code = "MR", Iso3Code = "MRT", Name = "Mauritania", Continent = "AF" },
                    new Country { Iso2Code = "MU", Iso3Code = "MUS", Name = "Mauritius", Continent = "AF" },
                    new Country { Iso2Code = "YT", Iso3Code = "MYT", Name = "Mayotte", Continent = "AF" },
                    new Country { Iso2Code = "MX", Iso3Code = "MEX", Name = "Mexico", Continent = "NA" },
                    new Country { Iso2Code = "FM", Iso3Code = "FSM", Name = "Micronesia, Federated States of", Continent = "OC" },
                    new Country { Iso2Code = "MD", Iso3Code = "MDA", Name = "Moldova", Continent = "EU" },
                    new Country { Iso2Code = "MC", Iso3Code = "MCO", Name = "Monaco", Continent = "EU" },
                    new Country { Iso2Code = "MN", Iso3Code = "MNG", Name = "Mongolia", Continent = "AS" },
                    new Country { Iso2Code = "ME", Iso3Code = "MNE", Name = "Montenegro", Continent = "EU" },
                    new Country { Iso2Code = "MS", Iso3Code = "MSR", Name = "Montserrat", Continent = "NA" },
                    new Country { Iso2Code = "MA", Iso3Code = "MAR", Name = "Morocco", Continent = "AF" },
                    new Country { Iso2Code = "MZ", Iso3Code = "MOZ", Name = "Mozambique", Continent = "AF" },
                    new Country { Iso2Code = "MM", Iso3Code = "MMR", Name = "Myanmar", Continent = "AS" },
                    new Country { Iso2Code = "NA", Iso3Code = "NAM", Name = "Namibia", Continent = "AF" },
                    new Country { Iso2Code = "NR", Iso3Code = "NRU", Name = "Nauru", Continent = "OC" },
                    new Country { Iso2Code = "NP", Iso3Code = "NPL", Name = "Nepal", Continent = "AS" },
                    new Country { Iso2Code = "NL", Iso3Code = "NLD", Name = "Netherlands", Continent = "EU" },
                    new Country { Iso2Code = "NC", Iso3Code = "NCL", Name = "New Caledonia", Continent = "OC" },
                    new Country { Iso2Code = "NZ", Iso3Code = "NZL", Name = "New Zealand", Continent = "OC" },
                    new Country { Iso2Code = "NI", Iso3Code = "NIC", Name = "Nicaragua", Continent = "NA" },
                    new Country { Iso2Code = "NE", Iso3Code = "NER", Name = "Niger", Continent = "AF" },
                    new Country { Iso2Code = "NG", Iso3Code = "NGA", Name = "Nigeria", Continent = "AF" },
                    new Country { Iso2Code = "NU", Iso3Code = "NIU", Name = "Niue", Continent = "OC" },
                    new Country { Iso2Code = "NF", Iso3Code = "NFK", Name = "Norfolk Island", Continent = "OC" },
                    new Country { Iso2Code = "MP", Iso3Code = "MNP", Name = "Northern Mariana Islands", Continent = "OC" },
                    new Country { Iso2Code = "NO", Iso3Code = "NOR", Name = "Norway", Continent = "EU" },
                    new Country { Iso2Code = "OM", Iso3Code = "OMN", Name = "Oman", Continent = "AS" },
                    new Country { Iso2Code = "PK", Iso3Code = "PAK", Name = "Pakistan", Continent = "AS" },
                    new Country { Iso2Code = "PW", Iso3Code = "PLW", Name = "Palau", Continent = "OC" },
                    new Country { Iso2Code = "PS", Iso3Code = "PSE", Name = "Palestinian Territory, Occupied", Continent = "AS" },
                    new Country { Iso2Code = "PA", Iso3Code = "PAN", Name = "Panama", Continent = "NA" },
                    new Country { Iso2Code = "PG", Iso3Code = "PNG", Name = "Papua New Guinea", Continent = "OC" },
                    new Country { Iso2Code = "PY", Iso3Code = "PRY", Name = "Paraguay", Continent = "SA" },
                    new Country { Iso2Code = "PE", Iso3Code = "PER", Name = "Peru", Continent = "SA" },
                    new Country { Iso2Code = "PH", Iso3Code = "PHL", Name = "Philippines", Continent = "AS" },
                    new Country { Iso2Code = "PN", Iso3Code = "PCN", Name = "Pitcairn", Continent = "OC" },
                    new Country { Iso2Code = "PL", Iso3Code = "POL", Name = "Poland", Continent = "EU" },
                    new Country { Iso2Code = "PT", Iso3Code = "PRT", Name = "Portugal", Continent = "EU" },
                    new Country { Iso2Code = "PR", Iso3Code = "PRI", Name = "Puerto Rico", Continent = "NA" },
                    new Country { Iso2Code = "QA", Iso3Code = "QAT", Name = "Qatar", Continent = "AS" },
                    new Country { Iso2Code = "RE", Iso3Code = "REU", Name = "Réunion", Continent = "AF" },
                    new Country { Iso2Code = "RO", Iso3Code = "ROU", Name = "Romania", Continent = "EU" },
                    new Country { Iso2Code = "RU", Iso3Code = "RUS", Name = "Russian Federation", Continent = "EU" },
                    new Country { Iso2Code = "RW", Iso3Code = "RWA", Name = "Rwanda", Continent = "AF" },
                    new Country { Iso2Code = "BL", Iso3Code = "BLM", Name = "Saint-Barthélemy", Continent = "NA" },
                    new Country { Iso2Code = "SH", Iso3Code = "SHN", Name = "Saint Helena", Continent = "AF" },
                    new Country { Iso2Code = "KN", Iso3Code = "KNA", Name = "Saint Kitts and Nevis", Continent = "NA" },
                    new Country { Iso2Code = "LC", Iso3Code = "LCA", Name = "Saint Lucia", Continent = "NA" },
                    new Country { Iso2Code = "MF", Iso3Code = "MAF", Name = "Saint-Martin (French part)", Continent = "NA" },
                    new Country { Iso2Code = "PM", Iso3Code = "SPM", Name = "Saint Pierre and Miquelon", Continent = "NA" },
                    new Country { Iso2Code = "VC", Iso3Code = "VCT", Name = "Saint Vincent and Grenadines", Continent = "NA" },
                    new Country { Iso2Code = "WS", Iso3Code = "WSM", Name = "Samoa", Continent = "OC" },
                    new Country { Iso2Code = "SM", Iso3Code = "SMR", Name = "San Marino", Continent = "EU" },
                    new Country { Iso2Code = "ST", Iso3Code = "STP", Name = "Sao Tome and Principe", Continent = "AF" },
                    new Country { Iso2Code = "SA", Iso3Code = "SAU", Name = "Saudi Arabia", Continent = "AS" },
                    new Country { Iso2Code = "SN", Iso3Code = "SEN", Name = "Senegal", Continent = "AF" },
                    new Country { Iso2Code = "RS", Iso3Code = "SRB", Name = "Serbia", Continent = "EU" },
                    new Country { Iso2Code = "SC", Iso3Code = "SYC", Name = "Seychelles", Continent = "AF" },
                    new Country { Iso2Code = "SL", Iso3Code = "SLE", Name = "Sierra Leone", Continent = "AF" },
                    new Country { Iso2Code = "SG", Iso3Code = "SGP", Name = "Singapore", Continent = "AS" },
                    new Country { Iso2Code = "SX", Iso3Code = "SXM", Name = "Sint Maarten (Dutch part)", Continent = "NA" },
                    new Country { Iso2Code = "SK", Iso3Code = "SVK", Name = "Slovakia", Continent = "EU" },
                    new Country { Iso2Code = "SI", Iso3Code = "SVN", Name = "Slovenia", Continent = "EU" },
                    new Country { Iso2Code = "SB", Iso3Code = "SLB", Name = "Solomon Islands", Continent = "OC" },
                    new Country { Iso2Code = "SO", Iso3Code = "SOM", Name = "Somalia", Continent = "AF" },
                    new Country { Iso2Code = "ZA", Iso3Code = "ZAF", Name = "South Africa", Continent = "AF" },
                    new Country { Iso2Code = "GS", Iso3Code = "SGS", Name = "South Georgia and the South Sandwich Islands", Continent = "AN" },
                    new Country { Iso2Code = "SS", Iso3Code = "SSD", Name = "South Sudan", Continent = "AF" },
                    new Country { Iso2Code = "ES", Iso3Code = "ESP", Name = "Spain", Continent = "EU" },
                    new Country { Iso2Code = "LK", Iso3Code = "LKA", Name = "Sri Lanka", Continent = "AS" },
                    new Country { Iso2Code = "SD", Iso3Code = "SDN", Name = "Sudan", Continent = "AF" },
                    new Country { Iso2Code = "SR", Iso3Code = "SUR", Name = "Suriname *", Continent = "SA" },
                    new Country { Iso2Code = "SJ", Iso3Code = "SJM", Name = "Svalbard and Jan Mayen Islands", Continent = "EU" },
                    new Country { Iso2Code = "SZ", Iso3Code = "SWZ", Name = "Swaziland", Continent = "AF" },
                    new Country { Iso2Code = "SE", Iso3Code = "SWE", Name = "Sweden", Continent = "EU" },
                    new Country { Iso2Code = "CH", Iso3Code = "CHE", Name = "Switzerland", Continent = "EU" },
                    new Country { Iso2Code = "SY", Iso3Code = "SYR", Name = "Syrian Arab Republic (Syria)", Continent = "AS" },
                    new Country { Iso2Code = "TW", Iso3Code = "TWN", Name = "Taiwan", Continent = "AS" },
                    new Country { Iso2Code = "TJ", Iso3Code = "TJK", Name = "Tajikistan", Continent = "AS" },
                    new Country { Iso2Code = "TZ", Iso3Code = "TZA", Name = "Tanzania *, United Republic of", Continent = "AF" },
                    new Country { Iso2Code = "TH", Iso3Code = "THA", Name = "Thailand", Continent = "AS" },
                    new Country { Iso2Code = "TL", Iso3Code = "TLS", Name = "Timor-Leste", Continent = "OC" },
                    new Country { Iso2Code = "TG", Iso3Code = "TGO", Name = "Togo", Continent = "AF" },
                    new Country { Iso2Code = "TK", Iso3Code = "TKL", Name = "Tokelau", Continent = "OC" },
                    new Country { Iso2Code = "TO", Iso3Code = "TON", Name = "Tonga", Continent = "OC" },
                    new Country { Iso2Code = "TT", Iso3Code = "TTO", Name = "Trinidad and Tobago", Continent = "NA" },
                    new Country { Iso2Code = "TN", Iso3Code = "TUN", Name = "Tunisia", Continent = "AF" },
                    new Country { Iso2Code = "TR", Iso3Code = "TUR", Name = "Turkey", Continent = "AS" },
                    new Country { Iso2Code = "TM", Iso3Code = "TKM", Name = "Turkmenistan", Continent = "AS" },
                    new Country { Iso2Code = "TC", Iso3Code = "TCA", Name = "Turks and Caicos Islands", Continent = "NA" },
                    new Country { Iso2Code = "TV", Iso3Code = "TUV", Name = "Tuvalu", Continent = "OC" },
                    new Country { Iso2Code = "UG", Iso3Code = "UGA", Name = "Uganda", Continent = "AF" },
                    new Country { Iso2Code = "UA", Iso3Code = "UKR", Name = "Ukraine", Continent = "EU" },
                    new Country { Iso2Code = "AE", Iso3Code = "ARE", Name = "United Arab Emirates", Continent = "AS" },
                    new Country { Iso2Code = "GB", Iso3Code = "GBR", Name = "United Kingdom", Continent = "EU" },
                    new Country { Iso2Code = "US", Iso3Code = "USA", Name = "United States of America", Continent = "NA" },
                    new Country { Iso2Code = "UM", Iso3Code = "UMI", Name = "United States Minor Outlying Islands", Continent = "OC" },
                    new Country { Iso2Code = "UY", Iso3Code = "URY", Name = "Uruguay", Continent = "SA" },
                    new Country { Iso2Code = "UZ", Iso3Code = "UZB", Name = "Uzbekistan", Continent = "AS" },
                    new Country { Iso2Code = "VU", Iso3Code = "VUT", Name = "Vanuatu", Continent = "OC" },
                    new Country { Iso2Code = "VE", Iso3Code = "VEN", Name = "Venezuela (Bolivarian Republic of)", Continent = "SA" },
                    new Country { Iso2Code = "VN", Iso3Code = "VNM", Name = "Viet Nam", Continent = "AS" },
                    new Country { Iso2Code = "VI", Iso3Code = "VIR", Name = "Virgin Islands, US", Continent = "NA" },
                    new Country { Iso2Code = "WF", Iso3Code = "WLF", Name = "Wallis and Futuna Islands", Continent = "OC" },
                    new Country { Iso2Code = "EH", Iso3Code = "ESH", Name = "Western Sahara", Continent = "AF" },
                    new Country { Iso2Code = "YE", Iso3Code = "YEM", Name = "Yemen", Continent = "AS" },
                    new Country { Iso2Code = "ZM", Iso3Code = "ZMB", Name = "Zambia", Continent = "AF" },
                    new Country { Iso2Code = "ZW", Iso3Code = "ZWE", Name = "Zimbabwe", Continent = "AF" }
                };

                db.Countries.AddRange(countries);
                db.SaveChanges();
            }
        }

        private static void EnsureUsersSeedData(backendDbContext db)
        {
            if (!db.Users.Any())
            {
                var users = new List<User>
                {
                    new User { Email = "eoinom@gmail.com", Password = "pass123", FirstName = "Eoin", LastName = "O'Malley" },
                    new User { Email = "joe.bloggs@gmail.com", Password = "pass123", FirstName = "Joe", LastName = "Bloggs" },
                    new User { Email = "paulmcc@applerecords.com", Password = "pass123", FirstName = "Paul", LastName = "McCartney" },
                    new User { Email = "john@imagine.com", Password = "pass123", FirstName = "John", LastName = "Lennon" },
                    new User { Email = "george@altavista.com", Password = "pass123", FirstName = "George", LastName = "Harrisson" },
                    new User { Email = "ringo@drummers4hire.com", Password = "pass123", FirstName = "Ringo", LastName = "Starr" }
                };

                db.Users.AddRange(users);
                db.SaveChanges();
            }
        }
    }
}
